build:
  image: golang
  environment:
    - REPO=golang-instagram
  commands:
    - go get -d github.com/xinhuang327/$REPO/...
    - cd $GOPATH/src/github.com/xinhuang327/$REPO/instagram
    - go get golang.org/x/net/proxy
    - go test -clientID=$$CLIENT_ID -accessToken=$$MY_TOK -myID=$$MY_ID
    - cd $GOPATH/src/github.com/xinhuang327/$REPO/auth_demo
    - go build
    - git clone http://$$GITAUTH@$$GITROOT/adrian/REL_$REPO $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - cp -r $GOPATH/src/github.com/xinhuang327/$REPO/* $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - cd $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - git add .
    - git config --global user.email "drone@example.com"
    - git config --global user.name "Drone"
    - git commit -m "Build for $$COMMIT"
    - git push