build:
  image: golang
  environment:
    - REPO=golang-instagram
  commands:
    - go get -d github.com/xinhuang327/$REPO/...
    - git clone http://$$GITAUTH@$$GITROOT/adrian/REL_$REPO $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - cp -r $GOPATH/src/github.com/xinhuang327/$REPO/* $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - cd $GOPATH/src/$$GITROOT/adrian/REL_$REPO
    - git add .
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - git commit -m "Another deploy release"
    - git push